### ISSUE TITLE
Error in example.php

### ISSUE THREAD

**Issue by gymadarasz** [TheFox/imapd#4]
Following the readme file, I have get a PHP Fatal error by running the example.php:
```
PHP Fatal error:  Call to a member function error() on null in /var/www/html/imapd_test/vendor/thefox/imapd/src/TheFox/Imap/Server.php on line 99
PHP Stack trace:
PHP   1. {main}() /var/www/html/imapd_test/server.php:0
PHP   2. TheFox\Imap\Server->listen() /var/www/html/imapd_test/server.php:23
```

**Comment by TheFox** [comment]
- Which imapd version are you using?
- Which PHP version are you using?

**Comment by gymadarasz** [comment]
Hi @TheFox,

Thank you for the quick response.

My PHP version was:
```
PHP 5.6.37-1+ubuntu16.04.1+deb.sury.org+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```
I'm not sure about the imapd version, I just quickly installed it via composer yesterday following your readme file: `composer.phar require thefox/imapd`, so I think it was the latest?

**Comment by TheFox** [comment]
The imapd version is in src/TheFox/Imap/Imapd.php. Please tell me what's your version. Since `composer.phar require thefox/imapd` normally uses the latest version from packagist.org, which is v0.5.0, and this version is only compatible with PHP 7, I'm not sure about what's going on.

**Comment by gymadarasz** [comment]
Ok, I think it is the issue. I'm not sure why but `$ composer require thefox/imapd` says `Using version ^0.3.0 for thefox/imapd` and also take "^0.3.0" into my `composer.json` file so I think this issue could be closed.
Thank you.

**Comment by TheFox** [comment]
> I'm not sure why but $ composer require thefox/imapd says Using version ^0.3.0 for thefox/imapd

This is because you are still using PHP 5. In order to use imapd version 0.4.0 (or higher) you have to install PHP 7.
